version: '3'
services:
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec foreman start -f Procfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/shirupedia
      - bundle:/usr/local/bundle
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password"
    depends_on:
      - db
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    restart: always
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

volumes:
  bundle:
    driver: local
