development:
  cloud_name: hajcm9hwg
  api_key: '959979495756699'
  api_secret: jD2kbiX1AUC0JzkK6-lyfei3v5I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hnj7qqu7w
  api_key: '756892682522774'
  api_secret: 5f1Ruur9dyUcLwzpIyWedTMAlt8
  enhance_image_tag: true
  static_image_support: true
